# site settings
title: Jasmine Lopez
subtitle:
email: lopez.jasmine094@gmail.com
description: I'm a software engineer based in Los Angeles, CA <br /> specializing in building high quality applications.
baseurl: ""
# the subpath of your site, e.g. /blog
url: jasminelopez.github.io
# the base hostname & protocol for your site
author:
street_address:
city: Fountain Valley
state: CA
zip_code: 92708
country: United States of America
phone: (815) 277 6912

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 5

# social settings
500px_url:
facebook_url:
github_url: https://github.com/jasminelopez
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/jasmineilopez
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
